#!/bin/bash
SECONDS=0
runhours=$((24*3600))
logfile=/var/log/memtester_$(date +%F_%H-%M-%S).log

icnt=0
rm $logfile
while [ true ];do
icnt=$((icnt+1))
echo $(date +%F_%H-%M-%S)......count: $icnt .......... >> $logfile
memtester 3G 1 2>&1|tee  -a $logfile
retval=${PIPESTATUS[0]}
if [ $retval -ne 0 ];then
echo memtest fail!!!
cat <<EOL


  ______      _____ _         _    ______ _____  _____   ____  _____    _ 
 |  ____/\   |_   _| |       | |  |  ____|  __ \|  __ \ / __ \|  __ \  | |
 | |__ /  \    | | | |       | |  | |__  | |__) | |__) | |  | | |__) | | |
 |  __/ /\ \   | | | |       | |  |  __| |  _  /|  _  /| |  | |  _  /  | |
 | | / ____ \ _| |_| |____   |_|  | |____| | \ \| | \ \| |__| | | \ \  |_|
 |_|/_/    \_\_____|______|  (_)  |______|_|  \_\_|  \_\\____/|_|  \_\ (_)
                                                                          
                                                                          


EOL
echo failed at $icnt times....
echo log are at /var/log/$logfile
break

fi

if [ $SECONDS -ge $runhours ];then
echo run over, pass!!

cat <<EOL

  _____         _____ _____    ____  _  __  _ 
 |  __ \ /\    / ____/ ____|  / __ \| |/ / | |
 | |__) /  \  | (___| (___   | |  | | ' /  | |
 |  ___/ /\ \  \___ \\___ \  | |  | |  <   | |
 | |  / ____ \ ____) |___) | | |__| | . \  |_|
 |_| /_/    \_\_____/_____/   \____/|_|\_\ (_)
                                              
                                              


EOL
break
fi

done

# timeout --preserve-status -s SIGINT 24h memtester 3G  2>&1|tee  -p  warn $logfile


